### ISSUE TITLE
How to inference on cluster task?

### ISSUE THREAD

**Issue by lsnls** [wwyi1828/CluSiam#7]
Hello, thank you for your great work!

How do I use the weights of the trained model to cluster images? I only found the code for model training in the repository.

I am looking forward to your reply. Thank you very much!

**Comment by wwyi1828** [comment]
Hi lsnls,

Thanks for your interest in our work! To use the trained model weights for clustering images, you can directly take the argmax of the output from model.cluster_assigner. 
the clustering task in our work is designed as an auxiliary pretext task to help the model learn useful representations. I did not initially expect the learned clusters can align well with the tumor/non-tumor in the C16.
